name: unit test spring boot app with jdk1.8
env:
  JAVA_VERSION: '8.0.282+8'                  # set this to the Java version to use
  DISTRIBUTION: adopt                  # set this to the Java distribution

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
      - name: maven install && unit test
        run: mvn install
        
# 

