name: unit test spring boot app with jdk1.8
env:
  JAVA_VERSION: '8.0.282+8'                  # set this to the Java version to use
  DISTRIBUTION: adopt                  # set this to the Java distribution

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3310:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tp2
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: loading database
        run: mysql -h 127.0.0.1 -P 33101 -uroot -proot tp2 --default-character-set=utf8
        
      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
      - name: maven install && unit test
        run: |
          cd api
          mvn install
          
  dingding-notify: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send dingding notify error
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 28dada9e5c1ef6c8766577813269aa2d60bea1a4ce0479ddc9100efa2f0ba9e8
          secret: SEC5690cf8d223fa96039ad9244d92d1238c303125dbc41c41e3fda2148a874d2c3
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "这个即将发布的新版本，创始人陈航（花名“无招”）称它为“红树林”。而在此之前，每当面临重大升级，产品经理们都会取一个应景的代号，这一次，为什么是“红树林”？",
                  "title": "执行失败",
                  "picUrl": "",
                  "messageUrl": "https://www.dingtalk.com/s?__biz=MzA4NjMwMTA2Ng==&mid=2650316842&idx=1&sn=60da3ea2b29f1dcc43a7c8e4a7c97a16&scene=2&srcid=09189AnRJEdIiWVaKltFzNTw&from=timeline&isappinstalled=0&key=&ascene=2&uin=&devicetype=android-23&version=26031933&nettype=WIFI"
              }
            }
      - name: Send dingding notify success
        if: ${{ success() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: 28dada9e5c1ef6c8766577813269aa2d60bea1a4ce0479ddc9100efa2f0ba9e8
          secret: SEC5690cf8d223fa96039ad9244d92d1238c303125dbc41c41e3fda2148a874d2c3
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "这个即将发布的新版本，创始人陈航（花名“无招”）称它为“红树林”。而在此之前，每当面临重大升级，产品经理们都会取一个应景的代号，这一次，为什么是“红树林”？",
                  "title": "执行成功",
                  "picUrl": "",
                  "messageUrl": "https://www.dingtalk.com/s?__biz=MzA4NjMwMTA2Ng==&mid=2650316842&idx=1&sn=60da3ea2b29f1dcc43a7c8e4a7c97a16&scene=2&srcid=09189AnRJEdIiWVaKltFzNTw&from=timeline&isappinstalled=0&key=&ascene=2&uin=&devicetype=android-23&version=26031933&nettype=WIFI"
              }
            }
        


