name: unit test spring boot app with jdk1.8
env:
  JAVA_VERSION: '8.0.282+8'                  # set this to the Java version to use
  DISTRIBUTION: adopt                  # set this to the Java distribution

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latestpull_request
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3310:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tp2
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: loading database
        run: |
          mysql -h 127.0.0.1 -P 3310 -uroot -proot tp2 --default-character-set=utf8
        
      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
      - name: maven install && unit test
        run: |
          cd api
          mvn install
          
      - name: 环境变量
        if: ${{ always() }}
        run : env
          
#   dingding-error: 
#     runs-on: ubuntu-latest
#     needs: build
#     if: ${{ failure() }}
#     steps:
#       - name: Send dingding notify error
#         uses: zcong1993/actions-ding@master
#         with:
#           dingToken: 28dada9e5c1ef6c8766577813269aa2d60bea1a4ce0479ddc9100efa2f0ba9e8
#           secret: SEC5690cf8d223fa96039ad9244d92d1238c303125dbc41c41e3fda2148a874d2c3
#           body: |
#             {
#               "msgtype": "text",
#               "text": {
#                   "content": '[打叉][打叉][打叉]\n提交者: ${{ github.triggering_actor }}\n${{ github.ref_type }}-pr: ${{ github.ref_name }}执行失败\n[${{ github.ref_type }}: ${{ github.server_url }}/${{ github.repository }}/${{ github.ref_name }}]'
#               }
#             }
      
#   dingding-success: 
#     runs-on: ubuntu-latest
#     needs: build
#     if: ${{ success() }}
#     steps:
#       - name: Send dingding notify success
#         uses: zcong1993/actions-ding@master
#         with:
#           dingToken: 28dada9e5c1ef6c8766577813269aa2d60bea1a4ce0479ddc9100efa2f0ba9e8
#           secret: SEC5690cf8d223fa96039ad9244d92d1238c303125dbc41c41e3fda2148a874d2c3
#           body: |
#             {
#               "msgtype": "text",
#               "text": {
#                   "content": '[微笑][微笑][微笑]\n提交者: ${{ github.triggering_actor }}\n${{ github.ref_type }}-pr: ${{ github.ref_name }}执行成功\n[${{ github.ref_type }}: ${{ github.server_url }}/${{ github.repository }}/${{ github.ref_name }}]'
#               }
#             }



