name: unit test spring boot app with jdk1.8
env:
  JAVA_VERSION: '8.0.282+8'                  # set this to the Java version to use
  DISTRIBUTION: adopt                  # set this to the Java distribution

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3310:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tp2
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: loading database
        run: mysql -h 127.0.0.1 -P 3310 -uroot -proot MYSQL_DATABASE --default-character-set=utf8
        
      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
      - name: maven install && unit test
        run: |
          cd api
          mvn install

